Import("env")


env.Append(
    CPPPATH=[
        "#/",
        "#/lib",
        # Ugly hack
        Dir("../assets/compiled"),
        Dir("../../icons"),
    ],
)


libs = env.BuildModules(
    [
        "mlib",
        "stm32wb",
        "freertos",
        "print",
        "microtar",
        "mbedtls",
        "toolbox",
        "libusb_stm32",
        "drivers",
        "fatfs",
        "flipper_format",
        "one_wire",
        "ibutton",
        "infrared",
        "subghz",
        "nfc",
        "digital_signal",
        "pulse_reader",
        "signal_reader",
        "u8g2",
        "lfrfid",
        "flipper_application",
        "music_worker",
        "uzlib",
        "mjs",
        "nanopb",
        "update_util",
        "momentum",
        "heatshrink",
        "ble_profile",
        "bit_lib",
        "datetime",
    ],
)

Return("libs")
